export interface Skin {
  id: string;
  name: string;
  category: "Classic" | "Fantasy" | "Sci-Fi" | "Modern" | "Cute";
  username: string; // The Minecraft username to fetch the skin from
}

export const SKINS: Skin[] = [
  { id: "1", name: "Dream", category: "Classic", username: "Dream" },
  { id: "2", name: "Technoblade", category: "Classic", username: "Technoblade" },
  { id: "3", name: "GeorgeNotFound", category: "Classic", username: "GeorgeNotFound" },
  { id: "4", name: "Sapnap", category: "Classic", username: "Sapnap" },
  { id: "5", name: "BadBoyHalo", category: "Classic", username: "BadBoyHalo" },
  { id: "6", name: "TommyInnit", category: "Classic", username: "TommyInnit" },
  { id: "7", name: "Tubbo", category: "Classic", username: "Tubbo" },
  { id: "8", name: "Ranboo", category: "Classic", username: "Ranboo" },
  { id: "9", name: "Philza", category: "Classic", username: "Phisnom" },
  { id: "10", name: "Wilbur Soot", category: "Classic", username: "WilburSoot" },
  { id: "11", name: "Quackity", category: "Classic", username: "Quackity" },
  { id: "12", name: "Karl Jacobs", category: "Classic", username: "KarlJacobs" },
  { id: "13", name: "Niki Nihachu", category: "Classic", username: "Nihachu" },
  { id: "14", name: "Eret", category: "Classic", username: "TheEret" },
  { id: "15", name: "Fundy", category: "Classic", username: "Fundy" },
  { id: "16", name: "Punz", category: "Classic", username: "Punz" },
  { id: "17", name: "Purpled", category: "Classic", username: "Purpled" },
  { id: "18", name: "Antfrost", category: "Classic", username: "Antfrost" },
  { id: "19", name: "Skeppy", category: "Classic", username: "Skeppy" },
  { id: "20", name: "CaptainSparklez", category: "Classic", username: "CaptainSparklez" },
  { id: "21", name: "DanTDM", category: "Classic", username: "DanTDM" },
  { id: "22", name: "Stampy", category: "Classic", username: "stampylonghead" },
  { id: "23", name: "PopularMMOs", category: "Classic", username: "PopularMMOs" },
  { id: "24", name: "GamingWithJen", category: "Classic", username: "GamingWithJen" },
  { id: "25", name: "EthosLab", category: "Classic", username: "Etho" },
  { id: "26", name: "Mumbo Jumbo", category: "Classic", username: "Mumbo" },
  { id: "27", name: "Grian", category: "Classic", username: "Grian" },
  { id: "28", name: "GoodTimesWithScar", category: "Classic", username: "GoodTimesWithScar" },
  { id: "29", name: "Iskall85", category: "Classic", username: "iskall85" },
  { id: "30", name: "Stressmonster101", category: "Classic", username: "stressmonster101" },
  { id: "31", name: "Zombie Hunter", category: "Fantasy", username: "Zombie" },
  { id: "32", name: "Skeleton King", category: "Fantasy", username: "Skeleton" },
  { id: "33", name: "Enderman Prince", category: "Fantasy", username: "Enderman" },
  { id: "34", name: "Creeper Lord", category: "Fantasy", username: "Creeper" },
  { id: "35", name: "Blaze Warrior", category: "Fantasy", username: "Blaze" },
  { id: "36", name: "Ghast Queen", category: "Fantasy", username: "Ghast" },
  { id: "37", name: "Wither Knight", category: "Fantasy", username: "Wither" },
  { id: "38", name: "Dragon Slayer", category: "Fantasy", username: "Dragon" },
  { id: "39", name: "Slime Mage", category: "Fantasy", username: "Slime" },
  { id: "40", name: "Spider Assassin", category: "Fantasy", username: "Spider" },
  { id: "41", name: "Cyberpunk", category: "Sci-Fi", username: "Cyber" },
  { id: "42", name: "Robot X", category: "Sci-Fi", username: "Robot" },
  { id: "43", name: "Space Explorer", category: "Sci-Fi", username: "Space" },
  { id: "44", name: "Alien Life", category: "Sci-Fi", username: "Alien" },
  { id: "45", name: "Future Soldier", category: "Sci-Fi", username: "Future" },
  { id: "46", name: "Neon Runner", category: "Sci-Fi", username: "Neon" },
  { id: "47", name: "Tech Guru", category: "Sci-Fi", username: "Tech" },
  { id: "48", name: "Laser Master", category: "Sci-Fi", username: "Laser" },
  { id: "49", name: "Void Walker", category: "Sci-Fi", username: "Void" },
  { id: "50", name: "Star Captain", category: "Sci-Fi", username: "Star" },
  { id: "51", name: "Modern Boy", category: "Modern", username: "Boy" },
  { id: "52", name: "Modern Girl", category: "Modern", username: "Girl" },
  { id: "53", name: "Streetwear", category: "Modern", username: "Street" },
  { id: "54", name: "Casual Style", category: "Modern", username: "Casual" },
  { id: "55", name: "Winter Outfit", category: "Modern", username: "Winter" },
  { id: "56", name: "Summer Vibes", category: "Modern", username: "Summer" },
  { id: "57", name: "Business Suit", category: "Modern", username: "Suit" },
  { id: "58", name: "Hoodie Life", category: "Modern", username: "Hoodie" },
  { id: "59", name: "Party Time", category: "Modern", username: "Party" },
  { id: "60", name: "Beach Day", category: "Modern", username: "Beach" },
];
